# -*- coding: utf-8 -*-
"""Test_pretain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##test de preentrenamiento
"""

!pip install pytest

import pandas as pd
from sklearn.linear_model import LinearRegression
import pytest

# Crear un DataFrame de ejemplo
data = {'X': [2022,2023,2024],
        'y': [2403161.9540813, 2483925.24059489, 2564688.52710849]}
df = pd.DataFrame(data)

# Dividir los datos en variables predictoras (X) y variable objetivo (y)
X = df[['X']]
y = df['y']

# Crear el modelo de regresión lineal
model = LinearRegression()

# Definir una prueba de preentrenamiento
def test_pretraining():
    # Asegurarse de que el modelo no está entrenado
    with pytest.raises(AssertionError):
        model.predict(X)

    # Entrenar el modelo
    model.fit(X, y)

    # Asegurarse de que el modelo está entrenado
    assert model.predict(X).shape[0] == y.shape[0]

# Ejecutar las pruebas de preentrenamiento
pytest.main(['-qq'])