# -*- coding: utf-8 -*-
"""Test_estat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##test estático
"""

!pip install pylint

import pandas as pd
from sklearn.linear_model import LinearRegression

# Crear un DataFrame de ejemplo
data = {'X': [2022,2023,2024],
        'y': [2403161.9540813, 2483925.24059489, 2564688.52710849]}
df = pd.DataFrame(data)

# Dividir los datos en variables predictoras (X) y variable objetivo (y)
X = df[['X']]
y = df['y']

# Crear y entrenar el modelo de regresión lineal
model = LinearRegression()
model.fit(X, y)

# Realizar una predicción
X_test = pd.DataFrame({'X': [2022,2023]})
y_pred = model.predict(X_test)

# Imprimir los resultados de la predicción
predictions = pd.DataFrame({'X': X_test['X'], 'y_pred': y_pred})
print(predictions)

# Realizar pruebas estáticas con pylint
# pylint: disable=E1101
mse = ((model.predict(X) - y) ** 2).mean()
print(f"MSE: {mse}")