# -*- coding: utf-8 -*-
"""mountain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/121f1n24W6TcXokl7cJIfWEOo_HilfuF9
"""

from google.colab import drive
drive.mount('/content/drive')

import urllib.request
import urllib.parse
import re

# Codificar la URL
url = "https://en.wikipedia.org/wiki/Áhkká"
encoded_url = urllib.parse.quote(url, safe=':/')

# Descargar el contenido de la página web
urllib.request.urlretrieve(encoded_url, "index.html")

# Leer el contenido descargado
with open("index.html", "r") as file:
    content = file.read()

# Extraer la información de la infobox
infobox_regex = r'<table class="infobox vcard".*?</table>'
infobox_data = re.findall(infobox_regex, content, re.DOTALL)

# Procesar y limpiar la información
processed_data = ""
for data in infobox_data:
    data = re.sub(r'<[^>]*>', '', data)  # Eliminar las etiquetas HTML
    data = re.sub(r'&#160;|&#8201;', ' ', data)  # Reemplazar entidades HTML por espacios
    data = re.sub(r'\n+', '\n', data)  # Eliminar líneas en blanco repetidas
    data = re.sub(r'\t+', '\t', data)  # Eliminar tabulaciones repetidas
    data = re.sub(r'(^|\n)\t*$', '', data)  # Eliminar líneas en blanco al final
    processed_data += data.strip() + "\n\n"

# Guardar la información en un archivo
with open("infobox.txt", "w") as file:
    file.write(processed_data)