# -*- coding: utf-8 -*-
"""Test_posttrain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##test de postentrenamiento
"""

!pip install pytest

import pandas as pd
from sklearn.linear_model import LinearRegression
import pytest

# Crear un DataFrame de ejemplo
data = {'X': [2022,2023,2024],
        'y': [2403161.9540813, 2483925.24059489, 2564688.52710849]}
df = pd.DataFrame(data)

# Dividir los datos en variables predictoras (X) y variable objetivo (y)
X = df[['X']]
y = df['y']

# Definir una prueba posterior al entrenamiento
def test_posttraining():
    # Hacer una predicción utilizando el modelo entrenado
    y_pred = model.predict(X)

    # Verificar que el número de muestras en la predicción sea igual al número de muestras en los datos
    assert y_pred.shape[0] == y.shape[0]

    # Verificar que las predicciones sean valores numéricos
    assert isinstance(y_pred[0], (int, float))

# Ejecutar las pruebas posteriores al entrenamiento
pytest.main(['-qq'])