# -*- coding: utf-8 -*-
"""test_post_train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qy9IgXVkLFaUT1UY95tp2ydaAHLBXSzk
"""

import joblib

def test_post_train():
    incremento_anual_model = open('/content/modelo_entrenado.pkl', 'rb')
    arbol_regresor = joblib.load(incremento_anual_model)
    assert arbol_regresor is not None, "Error: Model is not loaded"
    print ("listo")

test_post_train()