# -*- coding: utf-8 -*-
"""test_pre_train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qy9IgXVkLFaUT1UY95tp2ydaAHLBXSzk
"""

import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

def test_pre_train():
    df = pd.read_csv("/content/drive/MyDrive/Unitsdollars_Excel.csv", encoding="latin-1")
    # Eliminar las columnas que no son necesarias para el entrenamiento
    df.drop(['resource', 'variable', 'units', 'magnitude', 'source', 'flag'], axis=1, inplace=True)

    # Separar los datos de entrada (X) y las etiquetas de salida (y)
    X = df[['year']]
    y = df['data_value']  # No es necesario convertir a DataFrame aquí

    # Crear un modelo de regresión de árbol de decisión
    arbol_regresor = DecisionTreeRegressor()

    # Dividir los datos en conjuntos de entrenamiento y prueba
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

    assert X_train is not None, "Error: X_train is None"
    assert X_test is not None, "Error: X_test is None"
    assert y_train is not None, "Error: y_train is None"
    assert y_test is not None, "Error: y_test is None"
    print("listo")

test_pre_train()