# -*- coding: utf-8 -*-
"""Test_unit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##test unitario
"""

import unittest
import pandas as pd
from sklearn.linear_model import LinearRegression

class TestLinearRegression(unittest.TestCase):

    def setUp(self):
        # Crear un DataFrame de ejemplo para la prueba
        data = {'X': [2022,2023, 2024],
                'y': [2403161.9540813, 2483925.24059489, 2564688.52710849]}
        self.df = pd.DataFrame(data)

        # Dividir los datos en variables predictoras (X) y variable objetivo (y)
        self.X_train = self.df[['X']]
        self.y_train = self.df['y']

        # Crear y entrenar el modelo de regresión lineal
        self.model = LinearRegression()
        self.model.fit(self.X_train, self.y_train)

    def test_prediction(self):
        # Realizar una predicción con un valor de prueba
        X_test = pd.DataFrame({'X': [2023]})
        y_pred = self.model.predict(X_test)

        # Verificar que la predicción sea correcta
        self.assertEqual(y_pred, [2483925.24059489])

    def test_coefficients(self):
        # Verificar los coeficientes del modelo
        coef = self.model.coef_
        intercept = self.model.intercept_

        self.assertEqual(coef, [2])
        self.assertEqual(intercept, 0)

if __name__ == '__main__':
    unittest.main()