# -*- coding: utf-8 -*-
"""metricas_regline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##Métricas para regresión lineal
"""
from sklearn.metrics import mean_squared_error

# Evaluar el modelo utilizando el error cuadrático medio (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Error Cuadrático Medio (MSE):", mse)

# Calcular la raíz del error cuadrático medio (RMSE)
rmse = np.sqrt(mse)
print("Raíz del Error Cuadrático Medio (RMSE):", rmse)
