# -*- coding: utf-8 -*-
"""metricas_reglog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##Métricas para regresión logística
"""

# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

# Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

# Recall
from sklearn.metrics import recall_score
recall_score(y_test, y_pred, average=None)

# Precision
from sklearn.metrics import precision_score
precision_score(y_test, y_pred, average=None)