# -*- coding: utf-8 -*-
"""metricas_DecisionTreeClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13H-BMqDHfNFY27Af-tUgwXN00DBFxYs9

##Métricas para DecisionTreeClassifier
"""
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Crear y entrenar el modelo de clasificación
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = model.predict(X_test)

# Calcular las métricas
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

# Imprimir las métricas
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
